### ISSUE TITLE
Needs a Vision statement

### ISSUE THREAD

**Issue by IanDCarroll** [codelaboc/codelaboc.github.io#2]
As a potential contributor to the project, I would like there to be a simple vision statement explaining the mission of the webpage so that I can become personally committed and orient my contributions in a direction useful to that vision.

(A first large stroke to scrum and agile, if you want to go down that road. But my feelings wouldn't be hurt if you'd like to keep it more casual for now.)

**Comment by leighphan** [comment]
I'm open to applying agile/scrum to this. We do have an outline of the webpage so far.

Current version is up for suggestions and additional info before we move forward.

**Comment by IanDCarroll** [comment]
You've already got it partly there. You have a group Mission Statement:

> CodeLab aims to create an all-inclusive, welcoming, supportive community and environment to learn and build code.

I'll assume part of the vision for this website is to support that mission. Maybe something along the lines of "An information hub for people interested in CodeLab that allows them to get involved easily." 

If part of the plan is to use the actual web page as a thing CodeLab coders help build, that might be in there, too. But the idea is to clearly define the intention and objective without making any commitments as to how it will be achieved. 

This allows others to see the big picture, take ownership, and make higher quality contributions than if they were just code monkeys commanded to satisfy a spec. And allows enough technical vagueness so that the implementation can respond to changes.

**Comment by leighphan** [comment]
+1 to a Vision Statement. Helpful suggestions, @IanDCarroll.

Added a Vision Statement to the README file -- open to suggestions.
